name = "TableTraits"
uuid = "3783bdb8-4a98-5b6b-af9a-565f29a5fe9c"
version = "1.0.1"

[deps]
IteratorInterfaceExtensions = "82899510-4779-5014-852e-03e436cf321d"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "0.7, 1"
IteratorInterfaceExtensions = "^0.1.1, ^1"

[targets]
test = ["Test"]
